# Register image plugin for ckeditor
editor:
  config:
    importModules:
      - '@netresearch/rte-ckeditor-image'

  externalPlugins:
      typo3image: { route: "rteckeditorimage_wizard_select_image" }

processing:
  allowTagsOutside:
    - img
